services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:0.9.0
    container_name: nostr-relay
    restart: unless-stopped
    ports:
      - "7000:8080"
    environment:
      - PORT=8080
    volumes:
      - ./data:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml:ro
